services:
  db:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - ykw_network
    environment:
      POSTGRES_PASSWORD: wallet-test
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: your_keys_wallet_api
    hostname: ykw_api
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-wallet-test}
      - POSTGRES_USER=${POSTGRES_USER:-wallet-test}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-wallet-test}
    networks:
      - ykw_network
    volumes:
      - .:/yourkeyswallet
    ports:
      - "3000:3000"
    depends_on:
      - db

networks:
  ykw_network:
    driver: bridge